name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: install libgtest
      run: sudo apt-get install -y autoconf libgtest-dev libpthread-stubs0-dev
    - name: correct permissions
      run: chmod +x ./autogen.sh
    - name: autogen
      run: ./autogen.sh
    - name: configure
      run: ./configure
    - name: make check
      run: make check
